### ISSUE TITLE
Using Robo with Bamboo CI

### ISSUE THREAD

**Issue by zmilan** [Codegyre/Robo#100]
I need some help about using Robo with Bamboo CI to run Codeception tests. Currently status is that everything working fine until Robo finish its own tasks. It finish it successfully but than everything stop. In Bamboo there is one next task to parse xml response generated from tests and merged by Robo, but it never start.
Here is part from log file in Bamboo:
[Robo\Task\ExecTask] running export DISPLAY=:0 && java -jar selenium-server-standalone-2.43.1.jar -port 5555 -role node -hub http://privateIP:4444/hub/register
[Robo\Task\ParallelExecTask] php codecept.phar run --group login -c tests/frontend --no-exit --xml _log/acceptance.login.xml acceptance
[Robo\Task\ParallelExecTask] 1 processes ended in 41.40 s
[Codeception\Task\MergeXmlReportsTask] Merging JUnit XML reports into /home/bamboo/bamboo-agent-home/xml-data/build-dir/RP-AT-JOB1/tests/_output/result.xml
[Codeception\Task\MergeXmlReportsTask] Processing /home/bamboo/bamboo-agent-home/xml-data/build-dir/RP-AT-JOB1/tests/frontend/tests/_output/_log/acceptance.login.xml
[Codeception\Task\MergeXmlReportsTask] File /home/bamboo/bamboo-agent-home/xml-data/build-dir/RP-AT-JOB1/tests/_output/result.xml saved. 1 suites added
[Robo\Task\ExecTask] stopped java -jar selenium-server-standalone-2.43.1.jar -role hub

After this last line 'stopped java -jar selenium...' there is nothing more. Bamboo never move to next task and I need to stop it manually. 
Is there anyone who have experience with using Robo/Codeception with Bamboo CI, who can help me with this?

**Comment by boedah** [comment]
No real help sadly.
Had a hard time with Bamboo since using it.
E.g. had given up on supplying quoted commandline parameters to Robo via a Bamboo parameter...

Worked from the start with Jenkins :/

Maybe quickly try it out with Jenkins, then you will see, if the Problem lies in Bamboo.

**Comment by zmilan** [comment]
@boedah Thanks for reply. I will try to see with Jenkins, but I suppose we will need to go with Bamboo somehow... so I will still need to find some solution...

**Comment by boedah** [comment]
Yeah, we use both atm. But Bamboo can sometimes be a beast...

**Comment by zmilan** [comment]
Its look like preventing robo output solve issue. I had bamboo script task like this: php robo.phar bamboo:run-all and when I change it to this: php robo.phar bamboo:run-all > /dev/null 2>&1, it start to work. I was trying to use --quiet (-q) robo parameter also, but it still not prevent output from robo. I hope this will help someone else too :).

**Comment by boedah** [comment]
Glad you found a workaround, although its a hack :)

**Comment by zmilan** [comment]
I agree that its hack, but for now I not see any other solution. Its look like because of robo outputs bamboo cant know when task is done (success or fail) and block... I will for sure work more on this, since I'm not totally happy with result, but for now its good that I make first step :).
Thanks for help @boedah
