### ISSUE TITLE
CommandStack and ExecOneCommand cannot be used at the same time (since ExecOneCommand defines same property ($finishedAt))

### ISSUE THREAD

**Issue by boedah** [Codegyre/Robo#105]
New in Robo 0.5.0 (also see #87).

Prereq:
Task which extends CommandStack and wants to use ExecOneCommand (for arg, args, options).

* CommandStack uses ExecCommand uses Timer
* ExecOneCommand uses ExecCommand uses Timer

```
ERROR: Robo\Task\CommandStack and Robo\Common\ExecOneCommand define the same property ($finishedAt) in the composit
ion of Boedah\Robo\Task\Drush\DrushStack. This might be incompatible, to improve maintainability consider using acc
essor methods in traits instead.
```

**Comment by DavertMik** [comment]
Oh... I closed referenced task before I implemented Timer :)

**Comment by boedah** [comment]
Timer also does not need to be a trait actually. 

You could simply use https://packagist.org/packages/phpunit/PHP-timer for example.

**Comment by DavertMik** [comment]
I like traits a bit more than static calls.

**Comment by DavertMik** [comment]
@boedah oh, why do you need ExecOne + Stack? 

Stack is about running multiple commands one by one, ExecOne - to run exactly one command. 
Actually I didn't think of combining them together...

**Comment by DavertMik** [comment]
I think you still won't have a chance to include one into another because you still get conflicitng properties in this case :( 

----

`arg` and `option` will append arguments to exact one command.
while Stack will ask for a set of different commands. Not sure how they are expected to run with same arguments. In your case you might think to define your own *Stack class.

**Comment by DavertMik** [comment]
Btw, check latest update, I have removed some redundant methods from CommandStack

**Comment by boedah** [comment]
Reason behind wanting to use both is: for Drush you can set global arguments which must be used for each command (e.g. the drupal root directory and the site alias).

I will make a PR with a suggestion to be able to do this.

**Comment by DavertMik** [comment]
Thanks for explaining. I like your PR.

**Comment by boedah** [comment]
> I like traits a bit more than static calls.

But you can be in depencency hell...
A static Timer class can simply be used by any class who wants to use it...
Additionally, using e.g. PHP-timer would mean a little less NIH ;)
