### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by boedah** [Codegyre/Robo#106]
In my robo-drush update for Robo 0.5.0 I set `conflict` in composer.json to `~0.4`.

This did not work as the new Robo version does not follow semantic versioning. It should have been named `1.0.0`.
Had to change it to `<0.5.0`.

I think it would be good practice to use semver, what do you think?

**Comment by DavertMik** [comment]
Yes, you are right Robo should be stabilized to with strict namings and API. But I feel that 0.5.0 is not ready to become 1.0. Semver does not have any strict rules to 0.x versions, so I didn't break it :)

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by boedah** [comment]
Ok, you got me ;-) didn't know that. 
But v1 is only a symbolic barrier. 
From my point of view, Robo is way beyond one. So actually the 0.5 refactoring could have been 2.0...

**Comment by DavertMik** [comment]
nodejs and all its ecosystem is on version 0.x.x :) Nevertheless they do exist somehow )
I think we well keep evolving with small changing, trying different concepts, and namings. In one point Robo will get 1.0 release and maintanance plan to keep semver constraints.

Features I'd like to implement:

* Inclusion of commands from other classes than Robofile. 
* 3rd parties task installer via composer.
* Using 3rd party commands.
