### ISSUE TITLE
JSqueeze 2.0

### ISSUE THREAD

**Issue by nesl247** [Codegyre/Robo#127]
JSqueeze has been updated to 2.0.

**Comment by DavertMik** [comment]
Does it have api changes? 
If not it can be updated in `composer.json`, othwise we need to update the Minify task for it

**Comment by nesl247** [comment]
I have nothing to do with the project so I am not 100% sure. I did try changing my composer.json, and found out the namespace changed.

**Comment by burzum** [comment]
@nesl247 would you mind to test it? :)

**Comment by burzum** [comment]
Fixed.
