### ISSUE TITLE
Robo.phar syntax error

### ISSUE THREAD

**Issue by warrickhill** [Codegyre/Robo#150]
I got this error

PHP Parse error:  syntax error, unexpected T_USE, expecting T_FUNCTION in phar:///usr/local/bin/robo/src/Runner.php on line 15

what should i do?

**Comment by aaukt** [comment]
What version of PHP do you run?

Robo uses traits, which were introduced in PHP 5.4, if you run an earlier version you should update.

**Comment by burzum** [comment]
Closing this now because no further feedback was provided. @warrickhill Feel free to re-open it if you want to come back to this issue. Thank you.
