### ISSUE TITLE
Robo reports error even if suppressed

### ISSUE THREAD

**Issue by aaukt** [Codegyre/Robo#151]
If php encounters an error that is suppressed via the @ operator, Robo still reports it as an error after the task execution.

```php
class RoboFile extends \Robo\Tasks
{
    public function testError()
    {
        @unlink('/not/existing/file');
    }
}
```

I don't know if there is another solution than checking the triggering line for an @ and not report the error if this is the case.
It may not be a severe issue (i just encountered it in a doctrine command), but maybe it's worth thinking about.

**Comment by boedah** [comment]
Seems to be like that, yes.
We also had this failing our build.

But the @-operator is really bad practice, so this is the way to go: https://github.com/burzum/Robo/commit/4bcc7ec5eee51bc36250fed0e496a9abce111b61

But if it is in a thrid party lib, you seem to be out of luck.
Maybe submit a PR there?

**Comment by aaukt** [comment]
True that it is a bad practice and one could even argue that maybe PHP is not consistent in handling this.

There seems to be an easy solution to write a custom error-handler and check the error_reporting() for the current level (it will be 0 in case of a suppressed error).
I will create a PR later, then the maintainers can decide if they want to include it.

**Comment by burzum** [comment]
@DavertMik has the last word but if your PR is OK code wise I think this could be added. :+1:
