### ISSUE TITLE
Missing Build command in Codecept tasks?

### ISSUE THREAD

**Issue by javigomez** [Codegyre/Robo#162]
Not sure if is needed but, isn't the `build` missing at https://github.com/Codegyre/Robo/blob/master/src/Task/Testing/Codecept.php ?

I mean for when we do:

```
php vendor/bin/codecept build
```

**Comment by DavertMik** [comment]
Yes it can be added, however all other `Testing` commands just execute tests, so for consistency there were no `build` command there.

Probably it should be added but I don't see how :(
Should it be a new task like `CodeceptBuild`?

**Comment by javigomez** [comment]
`CodeceptBuild` sounds excellent to me. When I have time I will send a pull with it, but not sure when I will have some time free. If anyone can do it earlier please go ahead.

**Comment by boedah** [comment]
Back then when I played with codeception I always `build` before running the actual tests.

It could be the default to execute the build step before running test (as it also would not do any harm if nothing changes).
What do you think @DavertMik ?

**Comment by javigomez** [comment]
@boedah seems that is done by default: https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Codecept.php#L123-L126

**Comment by boedah** [comment]
Ah, ok, seems the `AutoBuild` slipped in by https://github.com/Codeception/Codeception/commit/9452f0c9ea7e1de8ef3e30423b47d4093f9ef73e.

But why would you need a Robo `build` task then?

**Comment by javigomez** [comment]
yup we don't need it anymore. Closing ^o^
