### ISSUE TITLE
Issue when executing Selenium with Robo in Travis

### ISSUE THREAD

**Issue by javigomez** [Codegyre/Robo#167]
I don't know the origin of this issue, but if I do this in my robo file in:

```php
...
    // launches Selenium server
    $this->taskExec('java -jar '.$pathToSelenium)
        ->background()
        ->run();
...
```

I get unexpected timeouts see:

![screen shot 2015-05-05 at 17 19 56](https://cloud.githubusercontent.com/assets/1375475/7489787/e3151e3e-f3da-11e4-816a-e28f37b51f0d.png)

However if I launch the Selenium-server-standalone in the travis.yml like:

![screen shot 2015-05-06 at 10 37 40](https://cloud.githubusercontent.com/assets/1375475/7489815/2838e7fc-f3db-11e4-9470-90a383c7da92.png)

Codeception executes smoothly:

![screen shot 2015-05-06 at 10 38 52](https://cloud.githubusercontent.com/assets/1375475/7489847/51f29c5a-f3db-11e4-882a-d790fcf5b58b.png)

Could the action of executing selenium-server-standalone.jar in Background affect to Codeception execution?

**Comment by burzum** [comment]
I doubt this is a problem of Robo, more likely with Codeception. The error message is pretty clearly telling you that the HTTP request timed out. It waited 30 seconds and didn't get any response from the called URL. The question is now if this should be catched by Codeception and considered as a bug or if it's up to you to handle it.

**Comment by DavertMik** [comment]
Probably the issue is with how background process is running, and it is related to Symfony Process library. However, I didn't encounter this issue locally. So maybe it is Travis-only

**Comment by javigomez** [comment]
I'm not getting the error anymore. Closing. Thanks
