### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by salarmehr** [Codegyre/Robo#172]
Hi, I'm new to Robo. How to use it for site deployment? 
Also how can I run all tasks sequentially?

**Comment by sensorario** [comment]
Me too, .. but I think this is not the right place to ask questions: try with http://robo.li/started/

**Comment by boedah** [comment]
We use Robo for deploying our sites.
Kind of Capistrano in PHP with a combination of Ssh and Rsync Tasks.

What do you mean by "all tasks sequentially"?
As tasks are just PHP methods, you can write a new task method calling other task methods in the order you like.

**Comment by burzum** [comment]
This question is far to broad, please read the documentation and try the examples.

If there is something specific that is not covered by the documentation ask on stackoverflow.com or here again. However, this is a bug tracker for reporting issues in the first place and not a support forum.
