### ISSUE TITLE
Running phantomJS in the background get's instantly stopped

### ISSUE THREAD

**Issue by gunfrank** [Codegyre/Robo#180]
```
public function phantomjsStart(){
        $this->taskExec('~/Projects/phantomjs-2.0.0/bin/phantomjs --webdriver=4444')
            ->background()
            ->run();
}
```
Running this task will result in the following output:
```
 [Exec] running ~/Projects/phantomjs-2.0.0/bin/phantomjs --webdriver=4444
 [Exec] stopped ~/Projects/phantomjs-2.0.0/bin/phantomjs --webdriver=4444
```

What am I doing wrong here?

**Comment by kostajh** [comment]
@gunfrank what were you doing wrong?

**Comment by boedah** [comment]
Nothing, I think, as this works as designed.

Robo stops all running jobs on destruction time (https://github.com/Codegyre/Robo/blob/master/src/Task/Base/Exec.php#L104), when it  receives a SIG_TERM or on shutdown of the PHP process (see https://github.com/Codegyre/Robo/blob/master/src/Task/Base/Exec.php#L165).

**Comment by MartinMystikJonas** [comment]
@boedah So how can I run process on background which will survive end of task?

**Comment by boedah** [comment]
@MartinMystikJonas: do you mean end of task or end of whole PHP process?
For surviving the end of a task function, I think it should work if you instantiate the Exec task in the constructor of your Robofile, and run it in your task function.

**Comment by MartinMystikJonas** [comment]
@boedah Survive end of PHP process. I want this to be used to start some processes which I need to be running during manual testing.

I solved this by executing bash script which then started process using nohup but I think this should be supported by Robo itself if possible.

**Comment by boedah** [comment]
Does it work when starting phantom itself with nohup (using Robo)?
