### ISSUE TITLE
When will v0.5.3 be released?

### ISSUE THREAD

**Issue by boedah** [Codegyre/Robo#182]
v0.5.2 is of 2015-02-24...

We need the `CopyDir` fixes (again) since there seems to be a bug in Symfony Mirror Dir (which we were using till Robo is released).
Using the current master works.

But an official v0.5.3 would be great!

**Comment by DavertMik** [comment]
Why not. What's with state of Pull Requests? Let's merge or reject everything we need and 0.5.3 is ready )

**Comment by boedah** [comment]
A quick overview:

* #169: is this generated? (think there are more "static" variables formatted wrongly)
* #173: Git task -> commented
* #166: this one is for you, I was confused by he naming...
* #165: your opinion needed about the shell escaping (like in many, many other tasks)
* #152: no response (already on hold)
* #143: no response (already on hold)
* #137: complex issue (also about shell escaping), also see #133 (already on hold)

But as all (except the small #169 and the Windows only #137) are features, I would rather release 0.5.3 more quickly as a bugfix release...

The others could come with 0.6.0?

**Comment by DavertMik** [comment]
done

**Comment by boedah** [comment]
:+1: !
