### ISSUE TITLE
Output debuging/informative messages to STDERR

### ISSUE THREAD

**Issue by MartinMystikJonas** [Codegyre/Robo#201]
I run into problem when trying tu use robo. Problem is that Robo outputs tons of information to STDOUT. But I need to process output of task I'm running (pipe it to another program).

Common approach is to output all debuging/informative messages to STDERR not to STDOUT so content of STDOUT is clean and can be processed. Is there any way how can do this with Robo?

**Comment by boedah** [comment]
I understand the point.
But also the other way could be required: only print anything to stderr, if it is a real error.
This is e.g. a problem in Drush on remote nodes.

If this is implemented in Robo, IMHO it has to be an option to be turned on: `redirectInternalRoboOutputToStderr()` or something like that ;)

**Comment by MartinMystikJonas** [comment]
Maybe it should be configurable by Config. Something like Config::setInternalOutput()

**Comment by MartinMystikJonas** [comment]
Quick fix I used is:
```
Config::setOutput(new StreamOutput(fopen('php://stderr', 'w')));
```

This redirects all output to stderr excepts what I explicitly send to stdout. It is not ideal but can be used for now.

**Comment by boedah** [comment]
Ah, ok. At first I thought you wanted to display the output of commands executed via ExecTask and all other output should go to stderr.

So you simply use `echo` in you tasks then?

**Comment by MartinMystikJonas** [comment]
Yes. I used this to redirec all output of tasks to stderr. If I want something explicitly redirected to stdout I echo it.

**Comment by greg-1-anderson** [comment]
Robo now uses a PSR-3 logger that sends all diagnostic output to stderr, so this has been done.
