### ISSUE TITLE
Create common abstract class for Less task and SCSS task

### ISSUE THREAD

**Issue by gabor-udvari** [Codegyre/Robo#205]
I would like to open a discussion about creating a common abstract class for the Less task and SCSS task and the methods the abstract class should have.

When I wrote the SCSS task (merged in #200) I copied the Less task so there is a lot of repeated code. This makes a double effort with bugfixes (#193 is now only applied to the Less task) and inconsistency with features (see [MAXakaWIZARD's comment](https://github.com/Codegyre/Robo/pull/193#discussion_r36404723) for implementing importDir)

The project [phpgearbox/asset](https://github.com/phpgearbox/asset) does the same thing, both Less and Scss extending the CSS class, but I would like more public methods, like addImportPath, setImportPaths and setFormatter which [leafo/scssphp](https://github.com/leafo/scssphp) has.

**Comment by DavertMik** [comment]
Yes, I saw some inconsistencies with `importPaths` of both classes. Probably we can have them refactored to use the same interface.

@MAXakaWIZARD what you think?

**Comment by MAXakaWIZARD** [comment]
@DavertMik  @gabor-udvari Thumbs up. I can do that if you have no objections.

**Comment by gabor-udvari** [comment]
@MAXakaWIZARD fine with me, go ahead.
