### ISSUE TITLE
Improved and consistent glob support

### ISSUE THREAD

**Issue by dlancea** [Codegyre/Robo#216]
Tasks seem to be updated piecemeal to include php's glob() function.

It would be helpful to:
1. Use a better glob function such as: https://github.com/webmozart/glob . This library supports an ant-like syntax, similar to what's used in gulp/grunt.
2. Implement glob functionality in every task that accepts files as input, for a more consistent API.

My suggestion would be to include a globbing function in Robo\Task\BaseTask or create a wrapper Glob class in the Robo\Common namespace (or maybe a larger FileSystem class with more common file tasks).

I think these changes would put Robo in better competition with other task runners.

**Comment by boedah** [comment]
:+1:

**Comment by dlancea** [comment]
In the mean time, to satisfy 1., you can use webmozart's glob in your robofile:

```php
use Webmozart\Glob\Glob;
use Webmozart\PathUtil\Path;

class RoboFile extends \Robo\Tasks{
	function assets(){
		// Get all .js files from the app javascript paths.
		$app_js = Glob::glob(Path::makeAbsolute('js/model/**/*.js', getcwd()));
		// concat app js files
		$this->taskConcat($app_js)
			->to(self::WEBROOT_PATH.'cache/js/models.js')
			->run();
	}
}
```

It would be nice if this was integrated, though.

**Comment by burzum** [comment]
:+1:

**Comment by gabor-udvari** [comment]
:+1: I relied on the globbing of Symfony 2 Finder for the [FlattenDir task](https://github.com/Codegyre/Robo/blob/adb287892c123e89e4354bb7bae7dec6853898da/src/Task/FileSystem/FlattenDir.php#L181), but I can see the the advantage of the Ant syntax.

**Comment by DavertMik** [comment]
Closed in favor of @233
