### ISSUE TITLE
Improve doc for beginners

### ISSUE THREAD

**Issue by ThomasFinnern** [Codegyre/Robo#227]
For the beginning i checked some own commands in RoboFile.php. These succedded
Then i wanted to put a group of my tasks into a own task file and i created a file with the name Check4ExistingIndexHtmlFile.php. When i started robo it always complained ....

So i thought i begin with the given example in "Getting startet",  Task
I copied the first part into .\CompileAssets.php and the second part into .\RoboFile.php.
Still i get the error

Fatal error: Trait 'CompileAssets' not found in C:\Entwickl\Entwickl.2015\GitHub\RSG2\RoboLiTasks\RoboFile.php on line 13
I am sure i do something wrong.

It may help if the needed structure is explained besides the examples 
(Name the files  and pathes)

------------------
By the way the "when" in following text may be replaced by "that"
So i recommend to replace 
`There is convention` **when** `all tasks should start ...`
with
`There is a convention` **that** `all tasks should start ...`
Regards Thomas

**Comment by DavertMik** [comment]
@ThomasFinnern it's hard to get from your post the idea how and what should be improved. Would you be so kind to send a PR with improvements you think should be done to docs? They are in this repo so it's pretty easy to start contributing )

**Comment by ThomasFinnern** [comment]
I would if i could ;-), My impression was that a certain folder structure is neccessary. Meaning: Do the task files included have to be besides the roboFile or in a seperate folder ? 
I was stuck with my attempt so i tried to use the two recommended files from the  "Getting startet" "Task" part but received above message. So something is wrong and the reason could not be solved with the introduction.

The first question is starting with `... A very basic task may look like: ...` 
Under which name and in which path should this demo part saved ?
May be some basic PHP is missing on my side but for my joomla project i am fluent in most cases.

**Comment by ThomasFinnern** [comment]
Didn't want to close it :-(

**Comment by boedah** [comment]
`Fatal error: Trait 'CompileAssets' not found in ` should be basically autoloading failing, right?
If it is, I think this is nothing which Robo should address in the documentation.

**Comment by ThomasFinnern** [comment]
The documentation should describe how to avoid this message. ;-)
I am not that familiar with PHP namespaces and don't know about traits.
So i just followed the documentation and tried to get the demo running but failed
What i find missing is a description to make it failsave as something must be wrong when i tried it

**Comment by ThomasFinnern** [comment]
Ok i start from scratch on my windows in an empty folder and tell what happens
1) Install via composer.json
When i openen a new composer.json file and added the code i did run into errors whe running composer install
a) Missing " around `required-dev` -> should be `"required-dev"`
b) Example is not complete for a beginner
I am coming for joomal to PHP to my first composer project to automate some parts of my component so i have no composer file to begin with
`require-dev: {
    "codegyre/robo": "*"
}`
brings error and needs to be 
`{
	"require-dev": {
	}
}`
2) Run of robo in commandline of windows 
Result on commandline: The command "robo" is either written wrong or could not be found
Added robo.bat file
`@echo off
php .\vendor\codegyre\robo\robo %*`
3) robo init creates RoboFile.php
>>robo hello thomas works
4) Tasks
The example looks like two files are used (Both parts begin wiht <?php
So i created a file CompileAssets.php where i put the first part and added the second part to RoboFile.php
The following is a big unknown as i startet from top
`It is recommended to have store trait loading task in loadTasks file of the same namespace`
How should the content look like
5) Running Robo build
Result:
`>robo build

Fatal error: Trait 'CompileAssets' not found in D:\Entwickl\Entwickl.2015\RoboLiTest01\RoboFile.php on line 10

Call Stack:
    1.0201     128384   1. {main}() D:\Entwickl\Entwickl.2015\RoboLiTest01\vendor\codegyre\robo\robo:0
    1.0298     273296   2. Robo\Runner->execute() D:\Entwickl\Entwickl.2015\RoboLiTest01\vendor\codegyre\robo\robo:19
    1.0955    1521840   3. Robo\Runner->loadRoboFile() D:\Entwickl\Entwickl.2015\RoboLiTest01\vendor\codegyre\robo\src\Runner.php:80
    1.0961    1525592   4. require_once('D:\Entwickl\Entwickl.2015\RoboLiTest01\RoboFile.php') D:\Entwickl\Entwickl.2015\RoboLiTest01\vendor\codegyre\robo\src\Runner.php:62

ERROR: Trait 'CompileAssets' not found
in D:\Entwickl\Entwickl.2015\RoboLiTest01\RoboFile.php:10`
---
That is why i recommended to impove this part of documentation
Of course it is up to you to keep the doc condensed for your intended audience

**Comment by burzum** [comment]
> I am not that familiar with PHP-namespaces and don't know about PHP-traits.

Honestly, this is not Robos fault nor it's duty to teach people php language features. Just look them up on php.net. This is nothing that requires days to learn. It's a matter hours, if hours at all.

All the other problems you encounter are also related to a lack of knowledge about Composer and how to set it up right. For example that you get the error message `The command "robo" is either written wrong or could not be found` means you haven't installed the package globally and probably didn't install composer globally as well.

Instead of trying to resolve problems that aren't in the scope of Robo you should try to use the documentation related to the problems: php.net's documentation and Composers documentation.

**Comment by ThomasFinnern** [comment]
so i tried to install robo global like the last time with command

`composer global require codegyre/robo`

but i am windows

See result
`d:\Entwickl\Entwickl.2016\_GitHub\RoboLiTasks>composer global require codegyre/robo
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Changed current directory to C:/Users/finnern/AppData/Roaming/Composer
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^0.6.0 for codegyre/robo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files`

So i am assuming that a) i did it before b) There is something missing or it is not possible on windows

**Comment by ThomasFinnern** [comment]
From the getting started:
>> To begin you need to create a Robofile. Just run robo init in empty dir:
>>  robo init

So i  created a robo.bat file containing "php c:\Users\finnern\AppData\Roaming\Composer\vendor\codegyre\robo\robo" command
and started it with 'robo init`

Copy of commandline window below

`d:\Entwickl\Entwickl.2016\_GitHub\RoboLiTasksNew>robo init

d:\Entwickl\Entwickl.2016\_GitHub\RoboLiTasksNew>php c:\Users\finnern\AppData\Roaming\Composer\vendor\codegyre\robo\robo

    Robo is not initialized here. Please run `robo init` to create a new RoboFile

Robo version 0.6.0

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help  Displays help for a command
  init  Intitalizes basic RoboFile in current dir
  list  Lists commands

d:\Entwickl\Entwickl.2016\_GitHub\RoboLiTasksNew>`

What d i have to do to get it running on windows . That may be the missing part of the documentation

**Comment by burzum** [comment]
> So i created a robo.bat file containing "php c:\Users\finnern\AppData\Roaming\Composer\vendor\codegyre\robo\robo" command
and started it with 'robo init`

This is again a problem of your environment and will affect *all* php shell scripts installed via composer. So you *really* want to create that *.bat file in *every* project? This is not Robo specific. If we would have to assume that everyone doesn't know their system and some of the common tools like git and composer every project would have to come with a complete documentation about that.

I don't know how you installed composer but AFAIR for me it registered the path in the environments $path variable automatically. Have a read about that, best in the order I've put them in the list.

* http://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them
* http://www.howtogeek.com/51807/how-to-create-and-use-global-system-environment-variables/
* http://serverfault.com/questions/88363/how-do-i-set-the-global-path-environment-in-a-batch-file
