### ISSUE TITLE
Check if files exist before using them

### ISSUE THREAD

**Issue by burzum** [Codegyre/Robo#231]
taskConcat() and taskMinify() do not seem to care if the file you try to use exists or not.

What about adding a generic method (could be implemented in a trait as well) that can be used in all tasks to check a string or an array (iterate over it) if it's a path or file and throw a hard error if it does not exist?

**Comment by DavertMik** [comment]
Yes, it should be added. Please do it )

**Comment by burzum** [comment]
Do you want to throw an exception or use one of the methods to print out an error? If yes, which one please. :)

**Comment by burzum** [comment]
@DavertMik whould this be good enough for you?

```php
<?php
namespace Robo\Common;

trait FileAndFolderCheck
{
	use IO;

	/**
	 * Checks if the given input is a file or folder.
	 *
	 * @param string|array $resources
	 * @param string $type "file", "dir", "both"
	 * @return void
	 */
	protected function checkResources($resources, $type)
	{
		if (is_string($resources)) {
			$resources = [$resources];
		}
		foreach ($resources as $resource) {
			switch ($type) {
				case 'file':
					if (!$this->isFile($resource)) {
						$this->printTaskError(sprintf('File "%s" does not exist!'), $this);
					}
				case 'dir':
					if (!$this->isDir($resource)) {
						$this->printTaskError(sprintf('Directory "%s" does not exist!'), $this);
					}
				case 'both':
					if (!($this->isDir($resource) || $this->isFile($resource))) {
						$this->printTaskError(sprintf('File or directory "%s" does not exist!'), $this);
					}
			}
		}
	}

	/**
	 * Convenience method to check the often uses "source => target" file / folder arrays.
	 *
	 * @param string|array $resources
	 * @return void
	 */
	protected function checkSourceAndTargetResource($resources) {
		if (is_string($resources)) {
			$resources = [$resources];
		}
		$sources = [];
		$targets = [];
		foreach ($resources as $source => $target) {
			$sources[] = $source;
			$target[] = $target;
		}
		$this->checkResources($sources);
		$this->checkResources($targets);
	}

	protected function isDir($directory)
	{
		return is_dir($directory);
	}

	protected function isFile($file)
	{
		return file_exists($file);
	}
}
```

**Comment by DavertMik** [comment]
```php
    protected function checkResources($resources, $type)
    {
        if (!in_array($type, ['file', 'dir', 'both'])) {
            throw new \InvalidArgumentException(sprintf('Invalid resource check of  type "%s" used!', $type));
        }
        if (is_string($resources)) {
            $resources = [$resources];
        }
```

1) I'd add resource types as constants (I think it is possible to attach constants to traits, or not)
2) 3) I'd set the `$type = 'both'` so to have default type
2) I'd rename `both` because it's hard to guess what is it all about without a context

**Comment by burzum** [comment]
1) Why constants? There is not really a need outside of this method for them and you'll add the constants to everything that uses the trait. So you'll give them a pretty unique - long - naming.

2) OK

3) What's your suggestion? fileAndDir?

**Comment by DavertMik** [comment]
1) It is a good practice of PHP to not rely on strings and use constants... Anyway, it is up to you. 
3) yes, `fileAndDir` would be ok, I think. But with bit-constants you could do it like `FILE & DIR` =)

**Comment by burzum** [comment]
1) I'm aware of this but it just makes sense in a case like UserRole::ADMIN or Gender::MALE. The values here are only used internally. Also by adding them to a trait will spread the constants across *all* tasks using the trait. FoobarTask::IS_DIR, SomeThingElseTask::IS_DIR...

2) OK

**Comment by DavertMik** [comment]
1) Agreed

**Comment by burzum** [comment]
Resolved by https://github.com/Codegyre/Robo/pull/238
