### ISSUE TITLE
Symfony 3 components not supported

### ISSUE THREAD

**Issue by pkruithof** [Codegyre/Robo#263]
We're using Robo in our (recently upgraded) Symfony 3 project. To help development of the RoboFile (with auto completion and such), we include Robo as a dev-dependency instead of a global phar. However due to the [henrikbjorn/lurker](https://github.com/henrikbjorn/Lurker/) dependency we cannot do this anymore, since it depends on 2.x versions of Symfony components.

I know this is an issue for that repository, but I can't find an issue tracker there, and was hoping maybe we can come to a solution for this together.

**Comment by DavertMik** [comment]
Thanks. will try to make it upgradable

**Comment by samvdb** [comment]
Any progress on this?

**Comment by greg-1-anderson** [comment]
henrikbjorn/lurker is now in require-dev, so Robo should work fine with Symfony 3.x now.

**Comment by pkruithof** [comment]
Nice, now for a new release to get the other [245 commits](https://github.com/Codegyre/Robo/compare/0.6.0...master) :wink:

**Comment by greg-1-anderson** [comment]
Now working towards a 1.0.0-beta1 release.
