### ISSUE TITLE
Tasks shouldn't call ask()

### ISSUE THREAD

**Issue by greg-1-anderson** [Codegyre/Robo#295]
See [the Scrutinizer report for GitHubRelease](https://scrutinizer-ci.com/g/Codegyre/Robo/inspections/76927144-a2d2-4989-9c7d-6f5d1032614c/code-structure/operation/Robo%5CTask%5CDevelopment%5CGitHubRelease%3A%3Arun).

When I reduced the coupling between the Robo task classes, I removed the IO trait from BaseTask.  Tasks that still need to do things such as call 'ask' may `use IO` on their own; however, it is better if the command does all of the asking, and passes the result as parameters to the task.

On a related note, the DynamicParams trait is useful for eliminating some typing when putting together a task, but the existence of a `call()` method makes things a little harder on the code analyzer, making errors look like warnings. Perhaps we could maintain this trait for use by third party tasks, but avoid using it in Robo core.

Waiting for feedback before taking action on any of this, though.

**Comment by greg-1-anderson** [comment]
Here are some things that still need to be fixed:
```
src/Task//Base/Exec.php: *  $this->say('tests passed');
src/Task//Base/ParallelExec.php:        $progress = new ProgressBar($this->getOutput());
src/Task//Base/ParallelExec.php:                        $this->getOutput()-> [various]
src/Task//Base/SymfonyCommand.php:            $this->command->run(new ArrayInput($this->input), $this->getOutput())
src/Task//Development/Changelog.php:        while ($resp = $this->ask("Changed in this release: ")) {
src/Task//Development/GitHub.php:        self::$user = $this->ask('GitHub User');
src/Task//Development/GitHub.php:        self::$pass = $this->askHidden('Password');
src/Task//Development/GitHub.php:            $this->askAuth();
src/Task//Development/GitHubRelease.php:        $this->name = $this->ask("Release Title");
src/Task//Development/GitHubRelease.php:        $this->body .= $this->ask("Description of Release\n") . "\n\n";
src/Task//Development/GitHubRelease.php:        while ($resp = $this->ask("Added in this release:")) {
src/Task//Development/PackPhar.php:        $progress = new ProgressBar($this->getOutput());
src/Task//Development/PackPhar.php:        $this->getOutput()->writeln('');
```
Notes:
- Use TaskIO for output, not `say` / `getOutput`
- Progress Bar should be provided as a service that tasks can use. e.g. provide a ProgressBarAwareInterface for tasks to implement. This would allow other libraries to pass in other sorts of progress indicators, and make it easier for tasks to implement progress output.
- `ask` should happen in the Command.

**Comment by greg-1-anderson** [comment]
Tasks that use DynamicParams:

- Archive/Extract.php
- Archive/Pack.php
- Base/ParallelExec.php
- CommandStack.php
- Development/Changelog.php
- Development/GenerateMarkdownDoc.php
- Development/GitHub.php
- File/Replace.php
- File/Write.php
- Remote/Rsync.php
- Remote/Ssh.php

**Comment by dustinleblanc** [comment]
I have used ask in this manner for project robo scripts:

```php
if ($this->ask("Would you like to foo?(y/n) === "y")
    $this->taskFoo();
}
```

or 
```php
$siteName = $this->ask("What is the site name?);
```
Im not entirely clear on the proposal but would it remove this kind of fluid call and response? I like these things being super accessible for new users, it was certainly a help to me when I started using Robo.

**Comment by greg-1-anderson** [comment]
The first example shows `ask` called from the command. This is the recommended way. The upshot is that `use IO` no longer appears in BaseTask. If your Robo scripts still work with Robo master, then they are fine.

It is unclear whether the second example is inside a command (RoboFile.php) or a task (e.g. taskFoo).  The solution I used in #296 is to pass an $io object (anything with `use IO`, e.g. a RoboFile object) into the task.  It would also be possible to just add the `use IO` to your task itself; then `ask` is available.

The downside of using IO in tasks is then, those tasks are only usable from code that has access to a full IO object, whereas tasks that do not ask may be used by any code that has a PSR-3 logger.

**Comment by greg-1-anderson** [comment]
The core tasks that must use IO (ParallelExec, PackPhar and SymfonyCommand) all `use IO`. The first two of these could stop using IO if we made a progress bar interface, as suggested above. That can be a follow-on issue. Once #296 and #297 are merged, this can be closed.

**Comment by greg-1-anderson** [comment]
I decoupled the progress bar from tasks in #300.

**Comment by greg-1-anderson** [comment]
Everything is done here; SymfonyCommand still uses IO, but must by design. The rest are fixed.
