### ISSUE TITLE
Naming things - changes to make prior to stable release

### ISSUE THREAD

**Issue by greg-1-anderson** [Codegyre/Robo#303]
It would be helpful to rename a couple of classes prior to 1.0 stable. Here are a few suggestions for discussion.

## Tasklib

This is a trait that is a collection of all of the `loadTasks` traits. Robo clients usually don't need to reference this trait directly, as it is included in Robo\Tasks. For classes that extend some other base class, though, it is helpful to be able to `use Tasklib` in order to add all of the task shortcuts.

A better name would be one that gave the reader an idea of what the trait contains; something like 'AllTasks', perhaps.

Example Usage:
```
class MyClassThatUsesTasks extends SomethingOtherThanRoboTasks
{
    use \Robo\AllTasks;
}
```
## TaskAccessor

This trait includes the `task()` function shortcut. TaskAccessor is included in Tasklib, so it is fairly unlikely that any clients will reference it directly.

Maybe 'TaskShortcutFunction' would be a better name for this trait.

Example Usage:
```
namespace Robo;

trait Tasklib \\ or 'trait AllTasks'
{
    use TaskShortcutFunction;
}
```
## Tasks

This is the base class for RoboFiles. The existing name is okay, since the function of this class is to contain tasks (see 'AllTasks' above). However, it might be even better to use a name that emphasizes the 'isa' relationship between this base class and the RoboFiles that extend it.  Maybe 'CommandFile'.

Example Usage:
```
class RoboFile extends \Robo\CommandFile
{
  
}
```
If the `Tasks` trait is renamed, then all RoboFiles would have to be adjusted. The other changes will have minimal impact.

**Comment by DavertMik** [comment]
1. Agree: Tasklib => Robo\LoadAllTasks
2. TaskAccessor is better to be as it is
3. \Robo\CommandFile... Let me imagine this file:

```php
<?php
class CommandFile implements ContainerAwareInterface
{
    use LoadAllTasks;
    use ContainerAwareTrait;
    use IO;

    protected function stopOnFail($stopOnFail = true)
    {
        Result::$stopOnFail = $stopOnFail;
    }
}
```

I don't see any command there... 
For compat reasons I'd like to leave this file as it is. 

`class Robofile extends Robo\Tasks` doesn't belong to Robo itself but to users who use Robo, so we need to make their tasks work. This change is not really important, so I'd like not to change it here.

**Comment by greg-1-anderson** [comment]
Cool. I will rename Tasklib to LoadAllTasks (c.f. #304) and leave the rest as-is.
