### ISSUE TITLE
Robo.phar out of date.

### ISSUE THREAD

**Issue by caseyfw** [Codegyre/Robo#325]
The version of robo hosted at robo.li/robo.phar has regressed to an old version (0.4.7 from 26 Dec 2014).

This is the same issue as #237 and #191.

It would seem there is a bug in the deployment pipeline.

**Comment by pingers** [comment]
`$ wget http://robo.li/robo.phar
--2016-05-02 11:15:24--  http://robo.li/robo.phar
Resolving robo.li (robo.li)... 192.30.252.153
Connecting to robo.li (robo.li)|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1643663 (1.6M) [application/octet-stream]
Saving to: 'robo.phar’

robo.phar           100%[===================>]   1.57M   317KB/s    in 5.4s    p

2016-05-02 11:15:29 (297 KB/s) - 'robo.phar’ saved [1643663/1643663]

$ php robo.phar
  RoboFile.php not found in this dir 
?    Should I create RoboFile here? (y/n)  
 y
RoboFile.php created
$ php robo.phar --version
Robo version 0.4.7`

**Comment by singularo** [comment]
Still an issue guys, can we get this resolved?

**Comment by raistlin** [comment]
@DavertMik ping

**Comment by deviantintegral** [comment]
I've published and signed a 1.0.0-beta1 release at https://github.com/deviantintegral/Robo/releases/tag/1.0.0-beta1 until this is resolved.

**Comment by DavertMik** [comment]
Thanks. I fucked up release script and I fucked up fixing it. Soooorryyyy
Started to work on it

**Comment by DavertMik** [comment]
Fixed that. It was because of changes to RoboFile and it was hard to notice them )
