### ISSUE TITLE
Argument with default value 'null' results in 'not enough arguments' exception

### ISSUE THREAD

**Issue by piwi91** [Codegyre/Robo#328]
Command:
`robo release`

Runs:
`public function release($branch = null, $version = null)`

Result:
```
  [Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "branch, version").
```

Expected:
A running command with default values `null`

**Comment by greg-1-anderson** [comment]
Fixed in https://github.com/consolidation-org/annotated-command/pull/29.

**Comment by greg-1-anderson** [comment]
Fixed on the `master` branch. We should make a bugfix release for this.

**Comment by pkruithof** [comment]
I'm waiting for a couple of other fixes as well. Can you tag a new release?

**Comment by greg-1-anderson** [comment]
@DavertMik: Could you tag a beta2 or 1.0.0?
