### ISSUE TITLE
Scrutinizer results no longer attached to PR results.

### ISSUE THREAD

**Issue by greg-1-anderson** [Codegyre/Robo#347]
Scrutinizer is still running on this repository; see https://scrutinizer-ci.com/g/Codegyre/Robo; however, Scrutizer results are no longer showing up on pull requests.  Any idea why this is?  I can't see the github settings for Robo.

**Comment by greg-1-anderson** [comment]
Now, Travis results are not shown with the PR either. See #349. This PR is not shown in Travis either, although a recent PR is: https://travis-ci.org/Codegyre/Robo/pull_requests

**Comment by greg-1-anderson** [comment]
Seems some folks are noticing operational problems on GitHub: https://mobile.twitter.com/danielbachhuber/status/734784618948231168

Maybe not our issue?

**Comment by greg-1-anderson** [comment]
Travis is back, and Coveralls (Coveralls are updated when Travis runs), but still no Scrutinizer.

@DavertMik: When you have a chance, maybe you could try removing and re-adding Robo from Scrutinizer.

**Comment by DavertMik** [comment]
I don't think it is a good idea to add/remove as we will loose stats for previous commits. 
Looks like Scrutinizer works. At least it has reports, you can check them on its site. I added you as maintainer.

Personally I don't think this reports should be added to PR reports unless they report bugs. And looks like I saw it working on https://github.com/Codegyre/Robo/pull/350

**Comment by DavertMik** [comment]
And I added you as admin at https://scrutinizer-ci.com/g/Codegyre/Robo

**Comment by greg-1-anderson** [comment]
Okay. I told Scrutinizer to use my github credentials instead of yours when calling the github API; we'll see if that makes any difference.  Even if it doesn't, let's just let it be.  As you said, the tests are running; they're just not attached to the PR.  They are not attached at #350 either; the inspection ran, but only Travis and Coverall results are visible from the github PR.

On a related note, I turned off 'post comments' on Coveralls, as those are not very interesting or helpful.

**Comment by greg-1-anderson** [comment]
Looks like Scrutinizer is back as of #355.  I don't know for sure if changing the credentials over is what did the trick; just glad it's working again, as I liked seeing the scrutinizer results in the PRs.
