### ISSUE TITLE
Aliases for $opts array and --options

### ISSUE THREAD

**Issue by scottwarren** [Codegyre/Robo#351]
Is there a way to have aliases for $opts including the --options values? [Example RoboFile](https://github.com/scottwarren/Example-Alias-for-Robo/blob/master/RoboFile.php).

`robo alias --tag-example="i should echo on the screen"`

Should output the same as `robo example --tag-example="i should echo on the screen"`

Which is: `Success! tag-example:i should echo on the screen` but instead it outputs:

```

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--tag-example" option does not exist.


alias <y>

```

**Comment by greg-1-anderson** [comment]
I put my recommendation in https://github.com/scottwarren/Example-Alias-for-Robo/compare/master...greg-1-anderson:patch-1.

Follow-up in https://github.com/consolidation-org/annotated-command

**Comment by scottwarren** [comment]
seems like you can't have class members for default variables in PHP @greg-1-anderson

**Comment by scottwarren** [comment]
`The default value must be a constant expression, not (for example) a variable, a class member or a function call.` see: http://php.net/manual/en/functions.arguments.php#functions.arguments.default

**Comment by greg-1-anderson** [comment]
`array(...)` is a constant expression, not a variable, nor a class member, nor a function call.  Worked for me in php 5.6, anyway.

Note that `[ ... ]` is php 5.4 or later, so you'd have to switch my example to `array(...)` if you're still on 5.3.

**Comment by scottwarren** [comment]
Thanks, I'll look into that, it was just that there seemed to be issues with the example, sorry, my mistake!

PS: thanks for looking into this you've been a great help :-), sorry for not thanking you earlier though!
