### ISSUE TITLE
Class CommandStack and Trait Executable cannot be used at the same time

### ISSUE THREAD

**Issue by boedah** [Codegyre/Robo#87]
In my Drush Task (https://github.com/boedah/robo-drush/blob/master/src/Drush.php#L51), I extend from CommandStack (to use `exec` and `run`) and use Trait Executable (to use `option` and `arg`).

The task fails with the latest Robo version (works with 0.4.4) with the message:

> ERROR: Robo\Task\Shared\CommandStack and Robo\Task\Shared\Executable define the same property ($workingDirectory) in the composition of Boedah\Robo\Task\DrushStackTask
. This might be incompatible, to improve maintainability consider using accessor methods in traits instead.

I could remove the extension from CommandStack but then have to copy and paste all but `printed()` and `dir()` (which is bad).

I think you could leverage this by renaming `workingDirectory` in CommandStack to something else (`workingDir`?).
Of course this would mean a BC break, if someone is already setting workingDirectory in CommandStack directly (and not via `dir()`).
Maybe you could also make this variable private?

Another option, which comes into my mind:
CommandStack and Executable both define `printed()` and `dir()`.
Maybe CommandStack can use Executable somehow?
But I think this is not easily possible (too much traits seem to get rather messy...).

What do you think?

**Comment by DavertMik** [comment]
Please check current master branch. I hope I resolved all collisions

**Comment by boedah** [comment]
@DavertMik: sadly not :( => #105.
