### ISSUE TITLE
Refactoring for 0.5.0. Comments needed!

### ISSUE THREAD

**Issue by DavertMik** [Codegyre/Robo#96]
# Robo Changes

1. **Tasks are located by following PSR-4 standard**
2. **Task loading by traits are removed** - this is done to simplify loading of tasks. Instead of declaring tasks in traits you can just call them with static initialization methods. Also you won't need to include lots of traits into RoboFile. Usage of static class calls instead of traits is aimed for simplicity. One task = one class = one file.
3. **Tasks initialization syntax changed to**

```php
<?php

taskChangelog::init()
    ->change('refactored Robo')
    ->version('0.5.0')
    ->run();
?>
```

For one-line tasks are simplified to:

```php
<?php
taskExec::_run('cap production deploy');

// equal to 
taskExec::init()
    ->exec('cap production deploy')
    ->run();

// also
taskCopyDir::_run(['/var/log', '/backup/log']);
taskCleanDir::_run(['web/assets','tmp/','log/']);
taskRename::_run('Dockerfile', 'tmpDockerfile');
?>
```

Those commands will initializa and invoke tasks;

4 **Stack tasks changes**

```php
<?php
// performs actions one by one
taskGit::stack()
    ->add('-A')
    ->commit("auto-update")
    ->pull()
    ->push()
    ->run();

// clones repo
taskGit::_clone('git@github.com:php-vcr/php-vcr.git');

// equal to
taskGit::stack()
    ->clone('git@github.com:php-vcr/php-vcr.git')
    ->run();
?>
```

This goes far well for **Exec**:

```php
<?php
// run 1 command
taskExec::_run('grunt test');

// run 2 commands
taskExec::stack()
    ->exec('grunt test')
    ->exec('phpunit')
    ->run();
?>
```

5 **RoboFile must contain a namespace** so FQNs could be simplified by IDE to proposed variants. Namespace can be either:

* robo
* Robo
* ????
* Robo;

6 **Directory Structure would be following:**

```
src/
  Command
    RoboUpdate
    RoboGlobalInstall
  
  Interfaces
    TaskInterface
    RunnableInterface

  Exception
    TaskException

  Commons
    Executable
    DynamicConfig
    CommandStack
    Output

  Task
    BaseTask
    FileSystem
        taskCleanDir
        taskDeleteDir
        task....
    Codeception\
        taskCodeceptRun
    PhpUnit\
        taskPhpUnit
    Minify\
        taskMinify
    Docker\
        task....
    Npm\
        taskNpmInstall
        taskNpmUpdate
    Rsync\
        taskRsync
    Svn\
        taskSvnStack
    Watch\
        taskWatch
    Exec\
        taskExec
        taskExecStack
```

**Comment by DavertMik** [comment]
@drobert  @AAlakkad  @boedah @jschnare @Rarst @SebSept @gunfrank @jonsa 
Happy new year, guys! 
What you think of it? 

I will refactor all current tasks to fit those changes, also I plan to leave traits as BC option for current files. So you don't have to upgrade Robofiles created with Robo < 0.5

**Comment by Rarst** [comment]
This feels clunkier to me.

I rather enjoy the current task flow in IDE:

1. Start with `$this`.
2. Pick the task from autocomplete method.
3. Chain what I need to do.
4. End with `run()`.

The suggestion seems more like following:

1. Start with autocomplete, figure out which `task*` Classes are actually Robo tasks and not something unrelated.
2. Stop to think is it a `stack()` kind of task or not.
3. Decide it's not and write it with `_run()` (underscore syntax tends to mean private btw, so now I am not sure if I am using something I am not supposed to directly).
3. Remember I need to add a chained call.
4. Go back and change `_run()` to `stack()`.
5. I mean to `init()`.
6. Change what was in `_run()` to... that method I can't remember because I use `_run()` half the time instead.

There is a lot more ambiguity in the process.

**Comment by DavertMik** [comment]
@Rarst Ok, I see the point. Sure, I see this is a controversial change. And sure we can use traits. But I don't like the way to have task initializers duplicated inside of traits. I.e. for every task we need a class + trait. Also you may have seen that `*Stack` tasks are much simplified in current model. 

For instance, if we take `PHPUnit` task, should it be made of 2 files: trait + class?
Or should we include all initializers into one trait? In this case a trait can be thought as a router...

**Comment by Rarst** [comment]
I would pose it like this — if the actual issue to solve is moving away from traits as implementation detail, can it be done _without_ API overhaul in first place?

For example one option would be to use `__call()` magic to instantiate classes instead of trait–provided methods.

**Comment by DavertMik** [comment]
@Rarst the problem with traits is about how many of them we need. 
If we have 1 trait per class it creates additional complexity. There will be issue with naming traits and classes as well - it would be hard to get what is factory and what is implementation.

> For example one option would be to use __call() magic to instantiate classes instead of trait–provided methods.

Could you provide an example?

**Comment by Rarst** [comment]
Basic magic example:

```php
class taskDemo
{
    public function __construct()
    {
        echo 'Hello world!';
    }
}
class RoboFile
{
    public function __call($name, $arguments)
    {
        if (class_exists($name)) {
            return new $name;
        }
    }
    public function test()
    {
        $this->taskDemo();
    }
}
(new RoboFile())->test();
```

I would guess for practical implementation it would be something like `interface TaskProvider` with procedure to register tasks for use.

**Comment by DavertMik** [comment]
Hm... I think this is a nice idea. In this case:

* tasks are loaded dynamically
* tasks for Robofile can be described with dockblocks (which are easier to define than traits)

On other hand:

* we should have all tasks to be in the same namespace? :(
* we still need to define magic methods and their parameters with dockblocks

**Comment by Rarst** [comment]
> we should have all tasks to be in the same namespace? :(

Not necessarily. Some sort of map would make sense, hashing tasks user-friendly name to its class. `'taskDemo' => 'Rarst\\Robo\\Tasks\\taskDemoOrSomething'`.

> we still need to define magic methods and their parameters with dockblocks

Yeah. With object composed in runtime there won't be really ideal convenience here. But I would choose end user convenience over internal implementation convenience.

**Comment by boedah** [comment]
Happy new year, too!

First thoughts:

1. I see no real problem in using traits (for tasks!):
 * they are explicit (no magic!)
 * they provide IDE auto-completion (and jump to definition!) out of the box
 * you can define public methods so they can be used directly on the command-line (we use this for some standard robo targets which can of course be overridden in the Robofile itself)
 * you could simply name the traits *Trait (e.g. PhpUnitTrait and PhpUnitTask) so there is no naming problem
 * the syntax: `$this->taskPHPUnit()->...` is really just syntactic sugar, I can easily instantiate a task myself in a Robofile
    * the `__call()`-magic could be added on top, so if you have to do additional logic, you can define the trait
    * but then I have to define the docblocks for the tasks themselves, which can get easily out of sync with the actial implementation (e.g. parameters)
1. the usage of traits for helper classes indeed sometimes poses a problem (see #87)
 * I do not know if traits are the best option here
1. `_run()` is a bad name, since it
 * clashes a little with `run()`
 * also reminds me of protected / private visibility
 * could be named `direct()` or something
1. why do i need to call `_clone()` for stacks which calls `clone()` but `_run()` which calls `exec()`?
1. stacks could be refactored so you can set global options for each command and executing multiple commands with these options prepended to each of them

I think it would be good if you make a list of what you are trying to achieve / which problems you want to solve. Because it is hard to guess (for me) using the above list.

**Comment by DavertMik** [comment]
> I think it would be good if you make a list of what you are trying to achieve / which problems you want to solve. Because it is hard to guess (for me) using the above list.

Good idea. If only I knew what I'm trying to achieve... :) But stop, it's not a refactoring for the sake of refactoring ) Here are my points:
* I'm trying to simplify Robo (in this case by removing redundant entity - trait)
* I'm trying to make Robo tasks PSR-4 ready
* I'm going to prepare Robo to have installable tasks (for not to keep them all in core)
* I'm going to organize directory structure so tasks, interfaces, exceptions, traits, were easy to locate (currently we have `Task` dir for all tasks and `Shared` for all other trash) 

-----
Anyway, guys you convinced me to keep traits.
I will publish a new proposal with less dramatic changes in it.

**Comment by Rarst** [comment]
I was going more for following point — if we want _better extension mechanism_ than traits, there is no need to start with _API overhaul_. :)

The list in your last comment is good, but still not completely actionable. Remember — not everyone has good idea about complete code base of the thing. :) I have contributed task, but even _then_ I hadn't looked closely at internals. It's a good thing (ease of contribution!), but it's also more barrier to discussing internals.

 - as above we probably _could_ get rid of traits, _without_ touching API
 - what isn't PSR-4 ready at the moment?
 - what are your goals for "installable" (might mean wildly different thing in different systems)?
 - moving folders around is least of it, yay for age of autoload :)

**Comment by drobert** [comment]
I think @Rarst's latest comments summarize my thoughts. That said, I actually think traits can make sense, just perhaps not the way they're currently in place (I'm 100% opposed to static initializers, but that's a whole other rant). 

If you consider the term 'trait' as just a word, it describes a characteristic. Given there a huge numbers of tasks potentially available, Robo is likely to end up with dozens and dozens of tasks. Including all of them as traits is of course not an extensible solution, and what I assume has prompted this thread. However, I would (in English) describe my build as a "composer, phpunit, apigen build". That's three characteristics, and it seems pretty reasonable for me to include PHP traits for each. 

Having said that, I don't think the effort of typing:
```php
(new MyTask(params, here())->chain()->stuff()->run() 
```
is all that burdensom compared with
```php
use MyTrait;
$this->myTrait(params, here)->chain()->stuff()->run()
```

So if we can determine there's a real-world convenience in using traits, I'm for them. As it stands, they don't really do much to help.

Anyway, my $0.02. Eagerly awaiting your replies to Rarst's questions, as I think those are the crux of the propopsed refactoring.

**Comment by DavertMik** [comment]
> what isn't PSR-4 ready at the moment?

One file with a task contain one trait and multiple tasks. 
So tasks can't be included in the way other than including trait :(

---------

Anyway, I think I will keep naming of tasks the way I proposed (with `task` prefixes).  but I will remove static initializers. Instead of them there will be traits.

Tasks will be located in `Task` dir/namespace. Some tasks are grouped (like FileSystem tasks), some are not like (Codeception, PhpUnit, ApiGen tasks);

Basic `Robo\Tasks` file may look like:

```
<?php
// include trait with all tasks like Exec
use Robo\Task\Base\Init;
use Robo\Task\PHPUnit\Init;
// load all development tasks
use Robo\Task\Development\Init;
use Robo\Task\FileSystem\Init;
use Robo\Task\Codeception\Init;
use Robo\Task\ApiGen\Init;
```

I.e. each task will be located in `Robo\Task\Name\taskName` class and have initialization trait `Robo\Task\Name\Init`

**Comment by boedah** [comment]
Some comments on latest version:

1. is this a left-over? https://github.com/Codegyre/Robo/blob/master/src/Task/Development/PhpServer.php#L39
1. maybe you should run some automated code-style fixer, since formatting in the whole codebase diverges sometimes

**Comment by DavertMik** [comment]
@boedah 

1. right, that should be removed
2. hm... I'm running PHPStorm and I'm ok with its formatting. Probably issues are with Pull Requests

**Comment by boedah** [comment]
2. Yeah, maybe only accept PRs with proper formatting. Could also put a task in RoboFile to automatically clean things up. Let my try a first shot. Always wanted to test that out :-D

**Comment by DavertMik** [comment]
@boedah good idea :+1:
