### ISSUE TITLE
Robo taskWatch monitor

### ISSUE THREAD

**Issue by Jandelson** [Codegyre/Robo#98]
public function watch()
    {
        $this->taskWatch()->monitor(...

Today I hum Process In Linux crontab What hum run php script in schedule A Day Given Once daily.

I can do this with robo using watch?

if you can help please thank you

**Comment by DavertMik** [comment]
No, robo watch is not for managing crontub processes.
It allows you to monitor directories for changes and perform actions on change, for instance you can run tests, or compile assets, when something changes

**Comment by Jandelson** [comment]
Thanks
